### ISSUE TITLE
genesis_block_generator hitting blockchain.info request quotas

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/pyethsaletool#5]
```
Gathered history: 9012
Processed transactions: 50
Processed transactions: 100
Processed transactions: 150
Processed transactions: 200
Processed transactions: 250
Processed transactions: 300
Processed transactions: 350
Processed transactions: 400
Traceback (most recent call last):
  File "genesis_block_generator.py", line 137, in <module>
    print json.dumps(evaluate(), indent=4)
  File "genesis_block_generator.py", line 129, in evaluate
    th = get_txs_and_heights(outs)
  File "genesis_block_generator.py", line 69, in get_txs_and_heights
    txs[h] = fetchtx(h)
  File "genesis_block_generator.py", line 50, in new_method
    c[str(arg)] = method(arg)
  File "/usr/local/lib/python2.7/site-packages/bitcoin/bci.py", line 341, in fetchtx
    return f(*args)
  File "/usr/local/lib/python2.7/site-packages/bitcoin/bci.py", line 268, in bci_fetchtx
    data = make_request('https://blockchain.info/rawtx/'+txhash+'?format=hex')
  File "/usr/local/lib/python2.7/site-packages/bitcoin/bci.py", line 23, in make_request
    raise Exception(p)
Exception: Quota Exceeded (Req Count Limit)
```

**Comment by wil611** [comment]
i have the same issue.

Processed transactions: 200
Processed transactions: 250
Processed transactions: 300
Traceback (most recent call last):
  File "genesis_block_generator.py", line 137, in <module>
    print json.dumps(evaluate(), indent=4)
  File "genesis_block_generator.py", line 129, in evaluate
    th = get_txs_and_heights(outs)
  File "genesis_block_generator.py", line 69, in get_txs_and_heights
    txs[h] = fetchtx(h)
  File "genesis_block_generator.py", line 50, in new_method
    c[str(arg)] = method(arg)
  File "/usr/local/lib/python2.7/dist-packages/bitcoin/bci.py", line 341, in fetchtx
    return f(*args)
  File "/usr/local/lib/python2.7/dist-packages/bitcoin/bci.py", line 268, in bci_fetchtx
    data = make_request('https://blockchain.info/rawtx/'+txhash+'?format=hex')
  File "/usr/local/lib/python2.7/dist-packages/bitcoin/bci.py", line 23, in make_request
    raise Exception(p)
Exception: Quota Exceeded (Req Count Limit)

**Comment by carryforward** [comment]
I saw this too.  It has caching, so after it times out and is restarted, the script skips over what it previously downloaded.  It will probably take over a dozen restarts to finish the script.

**Comment by vbuterin** [comment]
The newest script is in a different repo, and has a number of new safeguards to mitigate this including batch queries to reduce the total number of queries by ~20x. But do expect that it might happen and you may have to run the script a few times to get the full genesis block if you're building it at the same time everyone else is.
